use_frameworks!

target 'DDkeyboard_Example' do
  pod 'DDkeyboard', :path => '../'

  target 'DDkeyboard_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
